dist: focal
language: php
php:
    - 8.1.0
before_script:
    - composer install --no-progress --prefer-dist --optimize-autoloader --ignore-platform-reqs
script:
    - mkdir -p build/test
    - XDEBUG_MODE=coverage vendor/bin/phpunit -c phpunit.xml.dist
after_success:
    - travis_retry php vendor/bin/php-coveralls
    - travis_retry php vendor/bin/php-coveralls -v