name: CI/CD Github actions

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:

    test:
        name: Testing on PHP ${{ matrix.php-versions }}
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ ubuntu-latest ]
                php-versions: [ '8.1.0' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP Action
                uses: shivammathur/setup-php@2.11.0
                with:
                    php-version: ${{ matrix.php-versions }}
                    ini-values: memory_limit=512M
                    coverage: xdebug

            -   name: Install Composer dependencies
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Run rector
                run: vendor/bin/rector process --dry-run --clear-cache

            -   name: Run psalm
                run: vendor/bin/psalm --long-progress --no-cache --no-file-cache

            -   name: Run phpstan
                run: vendor/bin/phpstan analyse -c phpstan.neon

            -   name: Run phpcs
                run: vendor/bin/phpcs -p --colors --extensions=php --standard=PSR12 src tests

            -   name: Run phpunit
                run: vendor/bin/phpunit -c phpunit.xml.dist
